# Generated by BitRPC Protocol Generator
# File: protocol_factory.py
# Language: Python
# Date: 2025-10-08 00:56:42


from .runtime.bitrpc.serialization import BufferSerializer
from .serialization.registry import register_serializers

class ProtocolFactory:
    """Factory for initializing protocol components"""

    @staticmethod
    def initialize() -> None:
        """Initialize protocol serializers and components"""
        serializer = BufferSerializer.instance()
        register_serializers(serializer)
