// Generated by BitRPC Protocol Generator
// File: EchoResponse.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class EchoResponse
    {
        public string message { get; set; }
        public long timestamp { get; set; }
        public List<UserInfo> users { get; set; }
        public string server_time { get; set; }

        public EchoResponse()
        {
            message = string.Empty;
            timestamp = 0L;
            users = new List<UserInfo>();
            server_time = string.Empty;
        }
    }
}
