// Generated by BitRPC Protocol Generator
// File: EchoResponse.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class EchoResponse
    {
        public readonly static EchoResponse Default = new EchoResponse();

        public string message;
        public long timestamp;
        public List<UserInfo> users;
        public string server_time;

        public EchoResponse()
        {
            message = string.Empty;
            timestamp = 0L;
            users = new List<UserInfo>();
            server_time = string.Empty;
        }
    }
}
