// Generated by BitRPC Protocol Generator
// File: EchoRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class EchoRequest
    {
        public readonly static EchoRequest Default = new EchoRequest();

        public string message;
        public long timestamp;

        public EchoRequest()
        {
            message = string.Empty;
            timestamp = 0L;
        }
    }
}
