// Generated by BitRPC Protocol Generator
// File: GetUserResponse.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class GetUserResponse
    {
        public readonly static GetUserResponse Default = new GetUserResponse();

        public UserInfo user;
        public bool found;

        public GetUserResponse()
        {
            user = UserInfo.Default;
            found = false;
        }
    }
}
