// Generated by BitRPC Protocol Generator
// File: GetUserRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class GetUserRequest
    {
        public readonly static GetUserRequest Default = new GetUserRequest();

        public long user_id;

        public GetUserRequest()
        {
            user_id = 0L;
        }
    }
}
