// Generated by BitRPC Protocol Generator
// File: LoginRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class LoginRequest
    {
        public string username { get; set; }
        public string password { get; set; }

        public LoginRequest()
        {
            username = string.Empty;
            password = string.Empty;
        }
    }
}
