// Generated by BitRPC Protocol Generator
// File: LoginResponse.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class LoginResponse
    {
        public readonly static LoginResponse Default = new LoginResponse();

        public bool success;
        public UserInfo user;
        public string token;
        public string error_message;

        public LoginResponse()
        {
            success = false;
            user = UserInfo.Default;
            token = string.Empty;
            error_message = string.Empty;
        }
    }
}
