// Generated by BitRPC Protocol Generator
// File: LoginRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class LoginRequest
    {
        public readonly static LoginRequest Default = new LoginRequest();

        public string username;
        public string password;

        public LoginRequest()
        {
            username = string.Empty;
            password = string.Empty;
        }
    }
}
