// Generated by BitRPC Protocol Generator
// File: UserInfo.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public partial class UserInfo
    {
        public readonly static UserInfo Default = new UserInfo();

        public long user_id;
        public string username;
        public string email;
        public List<string> roles;
        public bool is_active;
        public DateTime created_at;

        public UserInfo()
        {
            user_id = 0L;
            username = string.Empty;
            email = string.Empty;
            roles = new List<string>();
            is_active = false;
            created_at = default;
        }
    }
}
