# Generated by BitRPC Protocol Generator
# File: LoginResponse_serializer.py
# Language: Python
# Date: 2025-10-08 00:56:41


from typing import Any
from .runtime.bitrpc.serialization import TypeHandler, BitMask, StreamWriter, StreamReader
from ..data.models import LoginResponse

class LoginResponseSerializer(TypeHandler):

    @property
    def hash_code(self) -> int:
        return 100275685

    def write(self, obj: LoginResponse, writer: StreamWriter) -> None:
        message: LoginResponse = obj
        mask = BitMask()

        # Bit mask group 0
        mask.set_bit(0, not self._is_default_bool(message.success))
        mask.set_bit(1, not self._is_default_struct(message.user))
        mask.set_bit(2, not self._is_default_string(message.token))
        mask.set_bit(3, not self._is_default_string(message.error_message))
        mask.write(writer)

        # Write field values
        if mask.get_bit(0):
            writer.write_bool(message.success)
        if mask.get_bit(1):
            writer.write_object(message.user)
        if mask.get_bit(2):
            writer.write_string(message.token)
        if mask.get_bit(3):
            writer.write_string(message.error_message)

    def read(self, reader: StreamReader) -> LoginResponse:
        message = LoginResponse()

        # Read bit mask group 0
        mask0 = BitMask()
        mask0.read(reader)

        if mask0.get_bit(0):
            message.success = reader.read_bool()
        if mask0.get_bit(1):
            message.user = reader.read_object()
        if mask0.get_bit(2):
            message.token = reader.read_string()
        if mask0.get_bit(3):
            message.error_message = reader.read_string()

        return message

    def _is_default_bool(self, value: bool) -> bool:
        return value == False

    def _is_default_struct(self, value: Any) -> bool:
        return value == None

    def _is_default_string(self, value: str) -> bool:
        return value == ""

