# Generated by BitRPC Protocol Generator
# File: models.py
# Language: Python
# Date: 2025-09-10 19:33:44


from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import datetime


@dataclass
class User:
    """
    name: str
    age: int
    email: str
    """

    name: str = ""
    age: int = 0
    email: str = ""

@dataclass
class Group:
    """
    name: str
    members: List[Any]
    description: str
    """

    name: str = ""
    members: List[Any] = field(default_factory=list)
    description: str = ""

@dataclass
class Organization:
    """
    name: str
    groups: List[Any]
    departments: List[str]
    leader: Any
    """

    name: str = ""
    groups: List[Any] = field(default_factory=list)
    departments: List[str] = field(default_factory=list)
    leader: Any = None

