# Generated by BitRPC Protocol Generator
# File: Organization_serializer.py
# Language: Python
# Date: 2025-09-10 19:33:44


from typing import Any
from bitrpc.serialization import TypeHandler, BitMask, StreamWriter, StreamReader
from ..data.models import Organization

class OrganizationSerializer(TypeHandler):

    @property
    def hash_code(self) -> int:
        return hash('Organization')

    def write(self, obj: Organization, writer: StreamWriter) -> None:
        message: Organization = obj
        mask = BitMask()

        # Bit mask group 0
        mask.set_bit(0, not self._is_default_string(message.name))
        mask.set_bit(1, not self._is_default_struct(message.groups))
        mask.set_bit(2, not self._is_default_string(message.departments))
        mask.set_bit(3, not self._is_default_struct(message.leader))
        mask.write(writer)

        # Write field values
        if mask.get_bit(0):
            writer.write_string(message.name)
        if mask.get_bit(1):
            writer.write_list(message.groups, lambda x: writer.write_object(x))
        if mask.get_bit(2):
            writer.write_list(message.departments, lambda x: writer.write_string(x))
        if mask.get_bit(3):
            writer.write_object(message.leader)

    def read(self, reader: StreamReader) -> Organization:
        message = Organization()

        # Read bit mask group 0
        mask0 = BitMask()
        mask0.read(reader)

        if mask0.get_bit(0):
            message.name = reader.read_string()
        if mask0.get_bit(1):
            message.groups = reader.read_list(lambda: reader.read_object())
        if mask0.get_bit(2):
            message.departments = reader.read_list(lambda: reader.read_string())
        if mask0.get_bit(3):
            message.leader = reader.read_object()

        return message

    def _is_default_string(self, value: str) -> bool:
        return value == ""

    def _is_default_struct(self, value: Any) -> bool:
        return value == None

