# Generated by BitRPC Protocol Generator
# File: registry.py
# Language: Python
# Date: 2025-09-10 19:33:44


from bitrpc.serialization import BufferSerializer

from .user_serializer import UserSerializer
from .group_serializer import GroupSerializer
from .organization_serializer import OrganizationSerializer

def register_serializers(serializer: BufferSerializer) -> None:
    """Register all protocol serializers"""
    serializer.register_handler(User, UserSerializer())
    serializer.register_handler(Group, GroupSerializer())
    serializer.register_handler(Organization, OrganizationSerializer())
