// Generated by BitRPC Protocol Generator
// File: SerializerRegistry.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using BitRPC.Serialization;

namespace Example.Protocol.Serialization
{
    public static class SerializerRegistry
    {
        public static void RegisterSerializers(IBufferSerializer serializer)
        {
            serializer.RegisterHandler<User>(new UserSerializer());
            serializer.RegisterHandler<Group>(new GroupSerializer());
            serializer.RegisterHandler<Organization>(new OrganizationSerializer());
        }
    }
}
