// Generated by BitRPC Protocol Generator
// File: UserSerializer.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using System.IO;
using BitRPC.Serialization;

namespace Example.Protocol.Serialization
{
    public class UserSerializer : ITypeHandler
    {
        public int HashCode => typeof(User).GetHashCode();

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (User)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
            // Bit mask group 0
            mask.SetBit(0, !IsDefault(message.name));
            mask.SetBit(1, !IsDefault(message.age));
            mask.SetBit(2, !IsDefault(message.email));
            mask.Write(writer);

            // Write field values
            if (mask.GetBit(0))
            {
                writer.WriteString(message.name);
            }
            if (mask.GetBit(1))
            {
                writer.WriteInt32(message.age);
            }
            if (mask.GetBit(2))
            {
                writer.WriteString(message.email);
            }
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new User();

            // Read bit masks using object pool
            BitRPC.Serialization.BitMask[] masks = new BitRPC.Serialization.BitMask[1];
            try
            {
            // Read bit mask group 0
            masks[0] = BitRPC.Serialization.BitMaskPool.Get(1);
            masks[0].Read(reader);
            if (masks[0].GetBit(0))
            {
                message.name = reader.ReadString();
            }
            if (masks[0].GetBit(1))
            {
                message.age = reader.ReadInt32();
            }
            if (masks[0].GetBit(2))
            {
                message.email = reader.ReadString();
            }
            return message;
            }
            finally
            {
                foreach (var mask in masks)
                {
                    if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        private bool IsDefault(string value)
        {
            return string.IsNullOrEmpty(value);
        }

        private bool IsDefault(int value)
        {
            return value == 0;
        }

    }
}
