# Generated by BitRPC Protocol Generator
# File: __init__.py
# Language: Python
# Date: 2026-07-31 00:34:02


"""
example.protocol Protocol Package
Generated by BitRPC Protocol Generator
"""

from .factory.protocol_factory import ProtocolFactory

__all__ = ['ProtocolFactory']
