# Generated by BitRPC Protocol Generator
# File: __init__.py
# Language: Python
# Date: 2025-10-08 00:56:42


"""
example.protocol Protocol Package
Generated by BitRPC Protocol Generator
"""

from .factory.protocol_factory import ProtocolFactory

__all__ = ['ProtocolFactory']
