// Generated by BitRPC Protocol Generator
// File: EchoResponseSerializer.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;

namespace Test.Protocol.Serialization
{
    public class EchoResponseSerializer : ITypeHandler
    {
        public int HashCode => -1786407677;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (EchoResponse)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
            // Bit mask group 0
            mask.SetBit(0, !IsDefault(message.message));
            mask.SetBit(1, !IsDefault(message.timestamp));
            mask.SetBit(2, !IsDefault(message.server_time));
            mask.Write(writer);

            // Write field values
            if (mask.GetBit(0))
            {
                writer.WriteString(message.message);
            }
            if (mask.GetBit(1))
            {
                writer.WriteInt64(message.timestamp);
            }
            if (mask.GetBit(2))
            {
                writer.WriteString(message.server_time);
            }
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new EchoResponse();

            // Read bit masks using object pool
            BitRPC.Serialization.BitMask[] masks = new BitRPC.Serialization.BitMask[1];
            try
            {
            // Read bit mask group 0
            masks[0] = BitRPC.Serialization.BitMaskPool.Get(1);
            masks[0].Read(reader);
            if (masks[0].GetBit(0))
            {
                message.message = reader.ReadString();
            }
            if (masks[0].GetBit(1))
            {
                message.timestamp = reader.ReadInt64();
            }
            if (masks[0].GetBit(2))
            {
                message.server_time = reader.ReadString();
            }
            return message;
            }
            finally
            {
                foreach (var mask in masks)
                {
                    if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        private bool IsDefault(string value)
        {
            return string.IsNullOrEmpty(value);
        }

        private bool IsDefault(long value)
        {
            return value == 0L;
        }

        private static readonly EchoResponseSerializer _instance = new EchoResponseSerializer();

        public static void Write(EchoResponse obj, BitRPC.Serialization.StreamWriter writer)
        {
            _instance.Write(obj, writer);
        }

        public static EchoResponse ReadStatic(BitRPC.Serialization.StreamReader reader)
        {
            return (EchoResponse)_instance.Read(reader);
        }

    }
}
