// Generated by BitRPC Protocol Generator
// File: LoginRequestSerializer.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;

namespace Test.Protocol.Serialization
{
    public class LoginRequestSerializer : ITypeHandler
    {
        public int HashCode => 175975135;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (LoginRequest)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
            // Bit mask group 0
            mask.SetBit(0, !IsDefault(message.username));
            mask.SetBit(1, !IsDefault(message.password));
            mask.Write(writer);

            // Write field values
            if (mask.GetBit(0))
            {
                writer.WriteString(message.username);
            }
            if (mask.GetBit(1))
            {
                writer.WriteString(message.password);
            }
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new LoginRequest();

            // Read bit masks using object pool
            BitRPC.Serialization.BitMask[] masks = new BitRPC.Serialization.BitMask[1];
            try
            {
            // Read bit mask group 0
            masks[0] = BitRPC.Serialization.BitMaskPool.Get(1);
            masks[0].Read(reader);
            if (masks[0].GetBit(0))
            {
                message.username = reader.ReadString();
            }
            if (masks[0].GetBit(1))
            {
                message.password = reader.ReadString();
            }
            return message;
            }
            finally
            {
                foreach (var mask in masks)
                {
                    if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        private bool IsDefault(string value)
        {
            return string.IsNullOrEmpty(value);
        }

        private static readonly LoginRequestSerializer _instance = new LoginRequestSerializer();

        public static void Write(LoginRequest obj, BitRPC.Serialization.StreamWriter writer)
        {
            _instance.Write(obj, writer);
        }

        public static LoginRequest ReadStatic(BitRPC.Serialization.StreamReader reader)
        {
            return (LoginRequest)_instance.Read(reader);
        }

    }
}
