// Generated by BitRPC Protocol Generator
// File: SerializerRegistry.cs
// Language: CSharp

using System;
using BitRPC.Serialization;

namespace Test.Protocol.Serialization
{
    public static class SerializerRegistry
    {
        public static void RegisterSerializers(IBufferSerializer serializer)
        {
            serializer.RegisterHandler<UserInfo>(new UserInfoSerializer());
            serializer.RegisterHandler<LoginRequest>(new LoginRequestSerializer());
            serializer.RegisterHandler<LoginResponse>(new LoginResponseSerializer());
            serializer.RegisterHandler<GetUserRequest>(new GetUserRequestSerializer());
            serializer.RegisterHandler<GetUserResponse>(new GetUserResponseSerializer());
            serializer.RegisterHandler<EchoRequest>(new EchoRequestSerializer());
            serializer.RegisterHandler<EchoResponse>(new EchoResponseSerializer());
        }
    }
}
