// Generated by BitRPC Protocol Generator
// File: EchoRequest_serializer.cpp
// Language: Cpp

#include "../include/echorequest_serializer.h"

namespace bitrpc {
namespace test::protocol {

int EchoRequestSerializer::hash_code() const { return 1660195677; }

void EchoRequestSerializer::write(const void* obj, StreamWriter& writer) const {
    const auto& obj_ref = *static_cast<const EchoRequest*>(obj);
    uint32_t mask0 = 0;
    if (!(obj_ref.message == "")) mask0 |= (1u << 0);
    if (!(obj_ref.timestamp == 0)) mask0 |= (1u << 1);
    writer.write_uint32(mask0);
    if (mask0 & (1u << 0)) { StringHandler::instance().write(&obj_ref.message, writer); }
    if (mask0 & (1u << 1)) { Int64Handler::instance().write(&obj_ref.timestamp, writer); }
}

void* EchoRequestSerializer::read(StreamReader& reader) const {
    auto obj_ptr = std::make_unique<EchoRequest>();
    uint32_t mask0 = reader.read_uint32();
    if (mask0 & (1u << 0)) { obj_ptr->message = *static_cast<std::string*>(StringHandler::instance().read(reader)); }
    if (mask0 & (1u << 1)) { obj_ptr->timestamp = *static_cast<int64_t*>(Int64Handler::instance().read(reader)); }
    return obj_ptr.release();
}

void EchoRequestSerializer::serialize(const EchoRequest& obj, StreamWriter& writer) { instance().write(&obj, writer); }
std::unique_ptr<EchoRequest> EchoRequestSerializer::deserialize(StreamReader& reader) { auto obj_ptr = std::unique_ptr<EchoRequest>(static_cast<EchoRequest*>(instance().read(reader))); return obj_ptr; }

}} // namespace bitrpc
