// Generated by BitRPC Protocol Generator
// File: EchoRequest_serializer.cpp
// Language: Cpp

#include "Test::Protocol/echorequest_serializer.h"

namespace bitrpc {
namespace Test::Protocol {

int EchoRequestSerializer::hash_code() const {
    return 1660195677;
}

void EchoRequestSerializer::write(const void* obj, StreamWriter& writer) const {
    const auto& obj_ref = *static_cast<const EchoRequest*>(obj);
    BitMask mask;

    // Bit mask group 0
    mask.set_bit(0, !is_default_string(obj_ref.message));
    mask.set_bit(1, !is_default_int64(obj_ref.timestamp));
    mask.write(writer);

    // Write field values
    if (mask.get_bit(0)) {
        writer.write_string(obj_ref.message);
    }
    if (mask.get_bit(1)) {
        writer.write_int64(obj_ref.timestamp);
    }
}

void* EchoRequestSerializer::read(StreamReader& reader) const {
    auto obj_ptr = std::make_unique<EchoRequest>();

    // Read bit mask group 0
    BitMask mask0;
    mask0.read(reader);

    if (mask0.get_bit(0)) {
        obj_ptr->message = reader.read_string();
    }
    if (mask0.get_bit(1)) {
        obj_ptr->timestamp = reader.read_int64();
    }
    return obj_ptr.release();
}
};

bool EchoRequestSerializer::is_default_string(const std::string& value) const {
    return value == "";
}
bool EchoRequestSerializer::is_default_int64(const int64_t& value) const {
    return value == 0;
}

}} // namespace bitrpc
