// Generated by BitRPC Protocol Generator
// File: models.cpp
// Language: Cpp

#include "Test::Protocol/models.h"

namespace bitrpc {
namespace Test::Protocol {

UserInfo::UserInfo() {
    user_id = 0;
    username = "";
    email = "";
    roles = {};
    is_active = false;
}

LoginRequest::LoginRequest() {
    username = "";
    password = "";
}

LoginResponse::LoginResponse() {
    success = false;
    token = "";
    error_message = "";
}

GetUserRequest::GetUserRequest() {
    user_id = 0;
}

GetUserResponse::GetUserResponse() {
    found = false;
}

EchoRequest::EchoRequest() {
    message = "";
    timestamp = 0;
}

EchoResponse::EchoResponse() {
    message = "";
    timestamp = 0;
    server_time = "";
}

}} // namespace bitrpc
