// Generated by BitRPC Protocol Generator
// File: models.cpp
// Language: Cpp

#include "../include/models.h"

namespace bitrpc {
namespace test::protocol {

UserInfo::UserInfo() {
    user_id = 0;
    username = "";
    email = "";
    roles = {};
    is_active = false;
    created_at = std::chrono::system_clock::time_point();
}

LoginRequest::LoginRequest() {
    username = "";
    password = "";
}

LoginResponse::LoginResponse() {
    success = false;
    token = "";
    error_message = "";
}

GetUserRequest::GetUserRequest() {
    user_id = 0;
}

GetUserResponse::GetUserResponse() {
    found = false;
}

EchoRequest::EchoRequest() {
    message = "";
    timestamp = 0;
}

EchoResponse::EchoResponse() {
    message = "";
    timestamp = 0;
    users = {};
    server_time = "";
}

}} // namespace bitrpc
