// Generated by BitRPC Protocol Generator
// File: protocol_factory.cpp
// Language: Cpp

#include "../include/protocol_factory.h"
#include "../include/serializer_registry.h"
#include "../runtime/serialization.h"

namespace bitrpc {
namespace example::protocol {

void ProtocolFactory::initialize() {
    auto& serializer = BufferSerializer::instance();
    register_serializers(serializer);
}

}} // namespace bitrpc
