// Generated by BitRPC Protocol Generator
// File: serializer_registry.cpp
// Language: Cpp

#include <bitrpc/serialization/buffer_serializer.h>

#include "Test::Protocol/userinfo_serializer.h"
#include "Test::Protocol/loginrequest_serializer.h"
#include "Test::Protocol/loginresponse_serializer.h"
#include "Test::Protocol/getuserrequest_serializer.h"
#include "Test::Protocol/getuserresponse_serializer.h"
#include "Test::Protocol/echorequest_serializer.h"
#include "Test::Protocol/echoresponse_serializer.h"

namespace bitrpc {
namespace Test::Protocol {

void register_serializers(BufferSerializer& serializer) {
    serializer.register_handler<UserInfo>(std::make_shared<UserInfoSerializer>());
    serializer.register_handler<LoginRequest>(std::make_shared<LoginRequestSerializer>());
    serializer.register_handler<LoginResponse>(std::make_shared<LoginResponseSerializer>());
    serializer.register_handler<GetUserRequest>(std::make_shared<GetUserRequestSerializer>());
    serializer.register_handler<GetUserResponse>(std::make_shared<GetUserResponseSerializer>());
    serializer.register_handler<EchoRequest>(std::make_shared<EchoRequestSerializer>());
    serializer.register_handler<EchoResponse>(std::make_shared<EchoResponseSerializer>());
}
}} // namespace bitrpc
