// Generated by BitRPC Protocol Generator
// File: serializer_registry.cpp
// Language: Cpp

#include "../include/serializer_registry.h"

namespace bitrpc {
namespace test::protocol {

void register_serializers(BufferSerializer& serializer) {
    serializer.register_handler<UserInfo>(std::make_shared<UserInfoSerializer>());
    serializer.register_handler<LoginRequest>(std::make_shared<LoginRequestSerializer>());
    serializer.register_handler<LoginResponse>(std::make_shared<LoginResponseSerializer>());
    serializer.register_handler<GetUserRequest>(std::make_shared<GetUserRequestSerializer>());
    serializer.register_handler<GetUserResponse>(std::make_shared<GetUserResponseSerializer>());
    serializer.register_handler<EchoRequest>(std::make_shared<EchoRequestSerializer>());
    serializer.register_handler<EchoResponse>(std::make_shared<EchoResponseSerializer>());
}
}} // namespace bitrpc
