// Generated by BitRPC Protocol Generator
// File: TestService_client.cpp
// Language: Cpp

#include "../include/testservice_client.h"

namespace bitrpc {
namespace test::protocol {

TestServiceClient::TestServiceClient(std::shared_ptr<IRpcClient> client)
    : BaseClient(client) {}

std::future<LoginResponse> TestServiceClient::LoginAsync(const LoginRequest& request) {
    return call_async<LoginRequest, LoginResponse>("TestService.Login", request);
}

std::future<GetUserResponse> TestServiceClient::GetUserAsync(const GetUserRequest& request) {
    return call_async<GetUserRequest, GetUserResponse>("TestService.GetUser", request);
}

std::future<EchoResponse> TestServiceClient::EchoAsync(const EchoRequest& request) {
    return call_async<EchoRequest, EchoResponse>("TestService.Echo", request);
}

std::shared_ptr<TestServiceClient> TestServiceClient::create_tcp_client(const std::string& host, int port) {
    auto tcp_client = RpcClientFactory::create_tcp_client(host, port);
    return std::make_shared<TestServiceClient>(tcp_client);
}
}} // namespace bitrpc
