// Generated by BitRPC Protocol Generator
// File: TestService_service_base.cpp
// Language: Cpp

#include "../include/testservice_service_base.h"

namespace bitrpc {
namespace test::protocol {

TestServiceServiceBase::TestServiceServiceBase() {
    register_methods();
}

void TestServiceServiceBase::register_methods() {
    register_async_method("Login", [this](const LoginRequest& request) {
        return LoginAsync_impl(request);
    });
    register_async_method("GetUser", [this](const GetUserRequest& request) {
        return GetUserAsync_impl(request);
    });
    register_async_method("Echo", [this](const EchoRequest& request) {
        return EchoAsync_impl(request);
    });
}

std::future<LoginResponse> TestServiceServiceBase::LoginAsync(const LoginRequest& request) {
    return LoginAsync_impl(request);
}

std::future<GetUserResponse> TestServiceServiceBase::GetUserAsync(const GetUserRequest& request) {
    return GetUserAsync_impl(request);
}

std::future<EchoResponse> TestServiceServiceBase::EchoAsync(const EchoRequest& request) {
    return EchoAsync_impl(request);
}

void TestServiceServiceBase::register_with_manager(ServiceManager& manager) {
    manager.register_service(std::make_shared<TestServiceServiceBase>());
}

}} // namespace bitrpc
