// Generated by BitRPC Protocol Generator
// File: TestService_client.cpp
// Language: Cpp

#include "Test::Protocol/testservice_client.h"

namespace bitrpc {
namespace Test::Protocol {

TestServiceClient::TestServiceClient(std::shared_ptr<RpcClient> client)
    : BaseClient(client) {}

std::future<LoginResponse> TestServiceClient::LoginAsync(const LoginRequest& request) {
    return call_async<LoginRequest, LoginResponse>("TestService.Login", request);
}

std::future<GetUserResponse> TestServiceClient::GetUserAsync(const GetUserRequest& request) {
    return call_async<GetUserRequest, GetUserResponse>("TestService.GetUser", request);
}

std::future<EchoResponse> TestServiceClient::EchoAsync(const EchoRequest& request) {
    return call_async<EchoRequest, EchoResponse>("TestService.Echo", request);
}

}} // namespace bitrpc
