// Generated by BitRPC Protocol Generator
// File: TestService_service_base.cpp
// Language: Cpp

#include "../include/testservice_service_base.h"

namespace bitrpc {
namespace test::protocol {

TestServiceServiceBase::TestServiceServiceBase() : BaseService("TestService") {
    register_methods();
}

void TestServiceServiceBase::register_methods() {
    register_async_method<LoginRequest, LoginResponse>("Login", [this](const LoginRequest& request) {
        return LoginAsync_impl(request);
    });
    register_async_method<GetUserRequest, GetUserResponse>("GetUser", [this](const GetUserRequest& request) {
        return GetUserAsync_impl(request);
    });
    register_async_method<EchoRequest, EchoResponse>("Echo", [this](const EchoRequest& request) {
        return EchoAsync_impl(request);
    });
}

std::future<LoginResponse> TestServiceServiceBase::LoginAsync(const LoginRequest& request) {
    return LoginAsync_impl(request);
}

std::future<GetUserResponse> TestServiceServiceBase::GetUserAsync(const GetUserRequest& request) {
    return GetUserAsync_impl(request);
}

std::future<EchoResponse> TestServiceServiceBase::EchoAsync(const EchoRequest& request) {
    return EchoAsync_impl(request);
}


}} // namespace bitrpc
