# Generated by BitRPC Protocol Generator
# File: __init__.py
# Language: Python
# Date: 2025-09-10 19:33:44


"""
example.protocol Protocol Package
Generated by BitRPC Protocol Generator
"""

from .factory.protocol_factory import ProtocolFactory

__all__ = ['ProtocolFactory']
