// Generated by BitRPC Protocol Generator
// File: EchoRequest_serializer.h
// Language: Cpp

#pragma once

#include "./serializer_registry.h"
#include "./models.h"

namespace bitrpc {
namespace test::protocol {

inline bool is_default_echorequest(const EchoRequest* value);
inline bool is_default_echorequest(const EchoRequest& value);

class EchoRequestSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;
    bool is_default(const void* obj) const override { return is_default_echorequest(static_cast<const EchoRequest*>(obj)); }

    static EchoRequestSerializer& instance() { static EchoRequestSerializer inst; return inst; }

    static void serialize(const EchoRequest& obj, StreamWriter& writer);
    static std::unique_ptr<EchoRequest> deserialize(StreamReader& reader);
};

inline bool is_default_echorequest(const EchoRequest* value) {
    if (value == nullptr) return true;
    const auto& obj = *value;
    if (obj.message != "") return false;
    if (obj.timestamp != 0) return false;
    return true;
}

inline bool is_default_echorequest(const EchoRequest& value) { return is_default_echorequest(&value); }

}} // namespace bitrpc
