// Generated by BitRPC Protocol Generator
// File: GetUserResponse_serializer.h
// Language: Cpp

#pragma once

#include "./serializer_registry.h"
#include "./models.h"

namespace bitrpc {
namespace example::protocol {

class GetUserResponseSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;
    bool is_default(const void* obj) const override { return is_default_getuserresponse(static_cast<const GetUserResponse*>(obj)); }

    static GetUserResponseSerializer& instance() { static GetUserResponseSerializer inst; return inst; }

    static void serialize(const GetUserResponse& obj, StreamWriter& writer);
    static std::unique_ptr<GetUserResponse> deserialize(StreamReader& reader);
};

}} // namespace bitrpc
