// Generated by BitRPC Protocol Generator
// File: GetUserResponse_serializer.h
// Language: Cpp

#pragma once

#include "./serializer_registry.h"

namespace bitrpc {
namespace test::protocol {

class GetUserResponseSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;

private:
    bool is_default_struct(const void*& value) const;
    bool is_default_bool(const bool& value) const;
};

}} // namespace bitrpc
