// Generated by BitRPC Protocol Generator
// File: GetUserRequest_serializer.h
// Language: Cpp

#pragma once

#include "./serializer_registry.h"
#include "./models.h"

namespace bitrpc {
namespace example::protocol {

class GetUserRequestSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;
    bool is_default(const void* obj) const override { return is_default_getuserrequest(static_cast<const GetUserRequest*>(obj)); }

    static GetUserRequestSerializer& instance() { static GetUserRequestSerializer inst; return inst; }

    static void serialize(const GetUserRequest& obj, StreamWriter& writer);
    static std::unique_ptr<GetUserRequest> deserialize(StreamReader& reader);
};

}} // namespace bitrpc
