// Generated by BitRPC Protocol Generator
// File: LoginRequest_serializer.h
// Language: Cpp

#pragma once

#include <bitrpc/serialization/type_handler.h>
#include "Test::Protocol/models.h"

namespace bitrpc {
namespace Test::Protocol {

class LoginRequestSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;

private:
    bool is_default_string(const std::string& value) const;
};

}} // namespace bitrpc
