// Generated by BitRPC Protocol Generator
// File: models.h
// Language: Cpp

#pragma once

#include <vector>
#include <string>
#include <chrono>

namespace bitrpc {
namespace example::protocol {

struct UserInfo {

    int64_t user_id;
    std::string username;
    std::string email;
    std::vector<std::string> roles;
    bool is_active;
    std::chrono::system_clock::time_point created_at;

    UserInfo();
};

struct LoginRequest {

    std::string username;
    std::string password;

    LoginRequest();
};

struct LoginResponse {

    bool success;
    UserInfo user;
    std::string token;
    std::string error_message;

    LoginResponse();
};

struct GetUserRequest {

    int64_t user_id;

    GetUserRequest();
};

struct GetUserResponse {

    UserInfo user;
    bool found;

    GetUserResponse();
};

struct EchoRequest {

    std::string message;
    int64_t timestamp;

    EchoRequest();
};

struct EchoResponse {

    std::string message;
    int64_t timestamp;
    std::vector<UserInfo> users;
    std::string server_time;

    EchoResponse();
};

// is_default declarations for generated messages
bool is_default_userinfo(const UserInfo* value);
bool is_default_userinfo(const UserInfo& value);
bool is_default_loginrequest(const LoginRequest* value);
bool is_default_loginrequest(const LoginRequest& value);
bool is_default_loginresponse(const LoginResponse* value);
bool is_default_loginresponse(const LoginResponse& value);
bool is_default_getuserrequest(const GetUserRequest* value);
bool is_default_getuserrequest(const GetUserRequest& value);
bool is_default_getuserresponse(const GetUserResponse* value);
bool is_default_getuserresponse(const GetUserResponse& value);
bool is_default_echorequest(const EchoRequest* value);
bool is_default_echorequest(const EchoRequest& value);
bool is_default_echoresponse(const EchoResponse* value);
bool is_default_echoresponse(const EchoResponse& value);

}} // namespace bitrpc
