// Generated by BitRPC Protocol Generator
// File: protocol_factory.h
// Language: Cpp

#pragma once

namespace bitrpc {
class BufferSerializer;
}

namespace bitrpc {
namespace test::protocol {

class ProtocolFactory {
public:
    static void initialize();
};

}} // namespace bitrpc
