// Generated by BitRPC Protocol Generator
// File: serializer_registry.h
// Language: Cpp

#pragma once

namespace bitrpc {
class BufferSerializer;
}

namespace bitrpc {
namespace Test::Protocol {

void register_serializers(BufferSerializer& serializer);

}} // namespace bitrpc
