// Generated by BitRPC Protocol Generator
// File: serializer_registry.h
// Language: Cpp

#pragma once

#include "../runtime/serialization.h"
#include "./userinfo_serializer.h"
#include "./loginrequest_serializer.h"
#include "./loginresponse_serializer.h"
#include "./getuserrequest_serializer.h"
#include "./getuserresponse_serializer.h"
#include "./echorequest_serializer.h"
#include "./echoresponse_serializer.h"

namespace bitrpc {
class BufferSerializer;
}

namespace bitrpc {
namespace test::protocol {

void register_serializers(BufferSerializer& serializer);

}} // namespace bitrpc
