// Generated by BitRPC Protocol Generator
// File: UserInfo_serializer.h
// Language: Cpp

#pragma once

#include "./serializer_registry.h"
#include "./models.h"

namespace bitrpc {
namespace example::protocol {

class UserInfoSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;
    bool is_default(const void* obj) const override { return is_default_userinfo(static_cast<const UserInfo*>(obj)); }

    static UserInfoSerializer& instance() { static UserInfoSerializer inst; return inst; }

    static void serialize(const UserInfo& obj, StreamWriter& writer);
    static std::unique_ptr<UserInfo> deserialize(StreamReader& reader);
};

}} // namespace bitrpc
