// Generated by BitRPC Protocol Generator
// File: EchoRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Test.Protocol
{
    public partial class EchoRequest
    {
        public string message { get; set; }
        public long timestamp { get; set; }

        public EchoRequest()
        {
            message = string.Empty;
            timestamp = 0L;
        }
    }
}
