// Generated by BitRPC Protocol Generator
// File: GetUserRequest.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Test.Protocol
{
    public partial class GetUserRequest
    {
        public long user_id { get; set; }

        public GetUserRequest()
        {
            user_id = 0L;
        }
    }
}
