// Generated by BitRPC Protocol Generator
// File: UserInfo.cs
// Language: CSharp

using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Test.Protocol
{
    public partial class UserInfo
    {
        public long user_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public List<string> roles { get; set; }
        public bool is_active { get; set; }
        public DateTime created_at { get; set; }

        public UserInfo()
        {
            user_id = 0L;
            username = string.Empty;
            email = string.Empty;
            roles = new List<string>();
            is_active = false;
            created_at = default;
        }
    }
}
