// Generated by BitRPC Protocol Generator
// File: ProtocolFactory.cs
// Language: CSharp

using System;
using BitRPC.Serialization;

namespace Test.Protocol.Factory
{
    public static class ProtocolFactory
    {
        public static void Initialize()
        {
            var serializer = BufferSerializer.Instance;
            Test.Protocol.Serialization.SerializerRegistry.RegisterSerializers(serializer);
        }
    }
}
