// Generated by BitRPC Protocol Generator
// File: iOrganizationService_service.h
// Language: Cpp
// Date: 2025-09-10 19:33:44


#pragma once

#include <future>

namespace bitrpc {
namespace example::protocol {

class IOrganizationServiceService {
public:
    virtual ~I{service.Name}Service() = default;
};

}} // namespace bitrpc
