// Generated by BitRPC Protocol Generator
// File: models.h
// Language: Cpp
// Date: 2025-09-10 19:33:44


#pragma once

#include <vector>
#include <string>
#include <optional>
#include <chrono>

namespace bitrpc {
namespace example::protocol {

struct User {

    std::string name;
    int32_t age;
    std::string email;

    User();
};

struct Group {

    std::string name;
    std::vector<void*> members;
    std::string description;

    Group();
};

struct Organization {

    std::string name;
    std::vector<void*> groups;
    std::vector<std::string> departments;
    void* leader;

    Organization();
};

}} // namespace bitrpc
