// Generated by BitRPC Protocol Generator
// File: OrganizationService_service_base.h
// Language: Cpp
// Date: 2025-09-10 19:33:44


#pragma once

#include <bitrpc/server/base_service.h>
#include "example::protocol/iorganizationservice_service.h"

namespace bitrpc {
namespace example::protocol {

class OrganizationServiceServiceBase : public BaseService, public IOrganizationServiceService {
public:
    OrganizationServiceServiceBase();

protected:
    void register_methods() override;
};

}} // namespace bitrpc
