// Generated by BitRPC Protocol Generator
// File: protocol_factory.h
// Language: Cpp
// Date: 2025-09-10 19:33:44


#pragma once

namespace bitrpc {
class BufferSerializer;
}

namespace bitrpc {
namespace example::protocol {

class ProtocolFactory {
public:
    static void initialize();
};

}} // namespace bitrpc
