// Generated by BitRPC Protocol Generator
// File: User_serializer.h
// Language: Cpp
// Date: 2025-09-10 19:33:44


#pragma once

#include <bitrpc/serialization/type_handler.h>
#include "example::protocol/models.h"

namespace bitrpc {
namespace example::protocol {

class UserSerializer : public TypeHandler {
public:
    int hash_code() const override;
    void write(const void* obj, StreamWriter& writer) const override;
    void* read(StreamReader& reader) const override;

private:
    bool is_default_string(const std::string& value) const;
    bool is_default_int32(const int32_t& value) const;
};

}} // namespace bitrpc
