// Generated by BitRPC Protocol Generator
// File: EchoResponseHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class EchoResponseHandler : ITypeHandler
    {
        public int HashCode => -1786407677;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (EchoResponse)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(2, !IsDefault(message.message),0);
                mask.SetBit(3, !IsDefault(message.timestamp),0);
                mask.SetBit(4, !IsDefault(message.users),0);
                mask.SetBit(5, !IsDefault(message.server_time),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(2, 0)) writer.WriteString(message.message);
                if (mask.GetBit(3, 0)) writer.WriteInt64(message.timestamp);
                if (mask.GetBit(4, 0)) writer.WriteList(writer.WriteUserInfo);
                if (mask.GetBit(5, 0)) writer.WriteString(message.server_time);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new EchoResponse();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(2, 0)) message.message = reader.ReadString();
                if (mask.GetBit(3, 0)) message.timestamp = reader.ReadInt64();
                if (mask.GetBit(4, 0)) message.users = reader.ReadList(reader.ReadUserInfo);
                if (mask.GetBit(5, 0)) message.server_time = reader.ReadString();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public EchoResponseHandler(){ _instance = this; }
        public static readonly EchoResponseHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(EchoResponse message){
            if (message == null) return true;
            if (!IsDefault(message.message)) return false;
            if (!IsDefault(message.timestamp)) return false;
            if (!IsDefault(message.users)) return false;
            if (!IsDefault(message.server_time)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteEchoResponse(EchoResponse message) => EchoResponseHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public EchoResponse ReadEchoResponse() => (EchoResponse)EchoResponseHandler._instance.Read(this);
    }
}
