// Generated by BitRPC Protocol Generator
// File: GetUserResponseHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class GetUserResponseHandler : ITypeHandler
    {
        public int HashCode => -1624387005;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (GetUserResponse)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(0, !IsDefault(message.user),0);
                mask.SetBit(1, !IsDefault(message.found),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(0, 0)) writer.WriteUserInfo(message.user);
                if (mask.GetBit(1, 0)) writer.WriteBool(message.found);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new GetUserResponse();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(0, 0)) message.user = reader.ReadUserInfo();
                if (mask.GetBit(1, 0)) message.found = reader.ReadBool();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public GetUserResponseHandler(){ _instance = this; }
        public static readonly GetUserResponseHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(GetUserResponse message){
            if (message == null) return true;
            if (!IsDefault(message.user)) return false;
            if (!IsDefault(message.found)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteGetUserResponse(GetUserResponse message) => GetUserResponseHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public GetUserResponse ReadGetUserResponse() => (GetUserResponse)GetUserResponseHandler._instance.Read(this);
    }
}
