// Generated by BitRPC Protocol Generator
// File: GetUserRequestHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class GetUserRequestHandler : ITypeHandler
    {
        public int HashCode => -1420445027;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (GetUserRequest)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(0, !IsDefault(message.user_id),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(0, 0)) writer.WriteInt64(message.user_id);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new GetUserRequest();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(0, 0)) message.user_id = reader.ReadInt64();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public GetUserRequestHandler(){ _instance = this; }
        public static readonly GetUserRequestHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(GetUserRequest message){
            if (message == null) return true;
            if (!IsDefault(message.user_id)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteGetUserRequest(GetUserRequest message) => GetUserRequestHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public GetUserRequest ReadGetUserRequest() => (GetUserRequest)GetUserRequestHandler._instance.Read(this);
    }
}
