// Generated by BitRPC Protocol Generator
// File: LoginRequestHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class LoginRequestHandler : ITypeHandler
    {
        public int HashCode => 175975135;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (LoginRequest)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(0, !IsDefault(message.username),0);
                mask.SetBit(1, !IsDefault(message.password),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(0, 0)) writer.WriteString(message.username);
                if (mask.GetBit(1, 0)) writer.WriteString(message.password);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new LoginRequest();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(0, 0)) message.username = reader.ReadString();
                if (mask.GetBit(1, 0)) message.password = reader.ReadString();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public LoginRequestHandler(){ _instance = this; }
        public static readonly LoginRequestHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(LoginRequest message){
            if (message == null) return true;
            if (!IsDefault(message.username)) return false;
            if (!IsDefault(message.password)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteLoginRequest(LoginRequest message) => LoginRequestHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public LoginRequest ReadLoginRequest() => (LoginRequest)LoginRequestHandler._instance.Read(this);
    }
}
