// Generated by BitRPC Protocol Generator
// File: LoginResponseHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class LoginResponseHandler : ITypeHandler
    {
        public int HashCode => 100275685;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (LoginResponse)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(0, !IsDefault(message.success),0);
                mask.SetBit(1, !IsDefault(message.user),0);
                mask.SetBit(2, !IsDefault(message.token),0);
                mask.SetBit(3, !IsDefault(message.error_message),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(0, 0)) writer.WriteBool(message.success);
                if (mask.GetBit(1, 0)) writer.WriteUserInfo(message.user);
                if (mask.GetBit(2, 0)) writer.WriteString(message.token);
                if (mask.GetBit(3, 0)) writer.WriteString(message.error_message);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new LoginResponse();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(0, 0)) message.success = reader.ReadBool();
                if (mask.GetBit(1, 0)) message.user = reader.ReadUserInfo();
                if (mask.GetBit(2, 0)) message.token = reader.ReadString();
                if (mask.GetBit(3, 0)) message.error_message = reader.ReadString();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public LoginResponseHandler(){ _instance = this; }
        public static readonly LoginResponseHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(LoginResponse message){
            if (message == null) return true;
            if (!IsDefault(message.success)) return false;
            if (!IsDefault(message.user)) return false;
            if (!IsDefault(message.token)) return false;
            if (!IsDefault(message.error_message)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteLoginResponse(LoginResponse message) => LoginResponseHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public LoginResponse ReadLoginResponse() => (LoginResponse)LoginResponseHandler._instance.Read(this);
    }
}
