// Generated by BitRPC Protocol Generator
// File: SerializerRegistry.cs
// Language: CSharp

using System;
using BitRPC.Serialization;

namespace Example.Protocol.Serialization
{
    public static class SerializerRegistry
    {
        public static void RegisterSerializers()
        {
            var serializer = BufferSerializer.Instance;
            serializer.RegisterHandler<UserInfo>(new UserInfoHandler());
            serializer.RegisterHandler<LoginRequest>(new LoginRequestHandler());
            serializer.RegisterHandler<LoginResponse>(new LoginResponseHandler());
            serializer.RegisterHandler<GetUserRequest>(new GetUserRequestHandler());
            serializer.RegisterHandler<GetUserResponse>(new GetUserResponseHandler());
            serializer.RegisterHandler<EchoRequest>(new EchoRequestHandler());
            serializer.RegisterHandler<EchoResponse>(new EchoResponseHandler());
        }
    }
}
