// Generated by BitRPC Protocol Generator
// File: UserInfoHandler.cs
// Language: CSharp

using System;
using System.IO;
using BitRPC.Serialization;
using System.Collections.Generic;
using static BitRPC.Serialization.Types;
using Example.Protocol.Serialization;

namespace Example.Protocol.Serialization
{
    public class UserInfoHandler : ITypeHandler
    {
        public int HashCode => 1876671786;

        public void Write(object obj, BitRPC.Serialization.StreamWriter writer)
        {
            var message = (UserInfo)obj;
            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                // Bit mask group 0
                mask.SetBit(0, !IsDefault(message.user_id),0);
                mask.SetBit(1, !IsDefault(message.username),0);
                mask.SetBit(2, !IsDefault(message.email),0);
                mask.SetBit(3, !IsDefault(message.roles),0);
                mask.SetBit(4, !IsDefault(message.is_active),0);
                mask.SetBit(5, !IsDefault(message.created_at),0);
                mask.Write(writer,1);

                // Write field values
                if (mask.GetBit(0, 0)) writer.WriteInt64(message.user_id);
                if (mask.GetBit(1, 0)) writer.WriteString(message.username);
                if (mask.GetBit(2, 0)) writer.WriteString(message.email);
                if (mask.GetBit(3, 0)) writer.WriteList(writer.WriteString);
                if (mask.GetBit(4, 0)) writer.WriteBool(message.is_active);
                if (mask.GetBit(5, 0)) writer.WriteDateTime(message.created_at);
            }
            finally
            {
                if (mask != null)
                {
                    BitRPC.Serialization.BitMaskPool.Return(mask);
                }
            }
        }

        public object Read(BitRPC.Serialization.StreamReader reader)
        {
            var message = new UserInfo();

            BitRPC.Serialization.BitMask mask = null;
            try
            {
                mask = BitRPC.Serialization.BitMaskPool.Get(1);
                mask.Read(reader, 1);
                if (mask.GetBit(0, 0)) message.user_id = reader.ReadInt64();
                if (mask.GetBit(1, 0)) message.username = reader.ReadString();
                if (mask.GetBit(2, 0)) message.email = reader.ReadString();
                if (mask.GetBit(3, 0)) message.roles = reader.ReadList(reader.ReadString);
                if (mask.GetBit(4, 0)) message.is_active = reader.ReadBool();
                if (mask.GetBit(5, 0)) message.created_at = reader.ReadDateTime();
                return message;
            }
            finally
            {
                if (mask != null) BitRPC.Serialization.BitMaskPool.Return(mask);
            }
        }

        public UserInfoHandler(){ _instance = this; }
        public static readonly UserInfoHandler _instance;
    }
}

namespace BitRPC.Serialization{
    public static partial class Types{
        public static bool IsDefault(UserInfo message){
            if (message == null) return true;
            if (!IsDefault(message.user_id)) return false;
            if (!IsDefault(message.username)) return false;
            if (!IsDefault(message.email)) return false;
            if (!IsDefault(message.roles)) return false;
            if (!IsDefault(message.is_active)) return false;
            if (!IsDefault(message.created_at)) return false;
            return true;
        }
    }
    public partial class StreamWriter{
        public void WriteUserInfo(UserInfo message) => UserInfoHandler._instance.Write(message, this);
    }
    public partial class StreamReader{
        public UserInfo ReadUserInfo() => (UserInfo)UserInfoHandler._instance.Read(this);
    }
}
