# Generated by BitRPC Protocol Generator
# File: OrganizationService_service_base.py
# Language: Python
# Date: 2025-09-10 19:33:44


from bitrpc.server import BaseService
from .iorganizationservice_service import IOrganizationServiceService

class OrganizationServiceServiceBase(BaseService, IOrganizationServiceService):
    """Base implementation for OrganizationService service"""

    def _register_methods(self) -> None:
        """Register service methods"""

