// Generated by BitRPC Protocol Generator
// File: OrganizationServiceClient.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using System.Threading.Tasks;
using BitRPC.Client;

namespace Example.Protocol.Client
{
    public class OrganizationServiceClient : BaseClient
    {
        public OrganizationServiceClient(IRpcClient client) : base(client)
        {
        }

    }
}
