// Generated by BitRPC Protocol Generator
// File: Group.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public class Group
    {
        public string name { get; set; }
        public List<User> members { get; set; }
        public string description { get; set; }

        public Group()
        {
            name = string.Empty;
            members = new List<User>();
            description = string.Empty;
        }
    }
}
