// Generated by BitRPC Protocol Generator
// File: User.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using System.Collections.Generic;
using BitRPC.Serialization;

namespace Example.Protocol
{
    public class User
    {
        public string name { get; set; }
        public int age { get; set; }
        public string email { get; set; }

        public User()
        {
            name = string.Empty;
            age = 0;
            email = string.Empty;
        }
    }
}
