// Generated by BitRPC Protocol Generator
// File: ComplexService_service_base.cpp
// Language: Cpp
// Date: 2025-09-10 18:57:31


#include "example::protocol/complexservice_service_base.h"

namespace bitrpc {
namespace example::protocol {

ComplexServiceServiceBase::ComplexServiceServiceBase() {
    register_methods();
}

void {service.Name}ServiceBase::register_methods() {
}

}} // namespace bitrpc
