// Generated by BitRPC Protocol Generator
// File: models.cpp
// Language: Cpp
// Date: 2025-09-10 19:33:44


#include "example::protocol/models.h"

namespace bitrpc {
namespace example::protocol {

User::User() {
    name = "";
    age = 0;
    email = "";
}

Group::Group() {
    name = "";
    members = {};
    description = "";
}

Organization::Organization() {
    name = "";
    groups = {};
    departments = {};
}

}} // namespace bitrpc
