// Generated by BitRPC Protocol Generator
// File: OrganizationService_service_base.cpp
// Language: Cpp
// Date: 2025-09-10 19:33:44


#include "example::protocol/organizationservice_service_base.h"

namespace bitrpc {
namespace example::protocol {

OrganizationServiceServiceBase::OrganizationServiceServiceBase() {
    register_methods();
}

void {service.Name}ServiceBase::register_methods() {
}

}} // namespace bitrpc
