// Generated by BitRPC Protocol Generator
// File: OrganizationService_client.cpp
// Language: Cpp
// Date: 2025-09-10 19:33:44


#include "example::protocol/organizationservice_client.h"

namespace bitrpc {
namespace example::protocol {

OrganizationServiceClient::OrganizationServiceClient(std::shared_ptr<RpcClient> client)
    : BaseClient(client) {}

}} // namespace bitrpc
