// Generated by BitRPC Protocol Generator
// File: serializer_registry.cpp
// Language: Cpp
// Date: 2025-09-10 19:33:44


#include <bitrpc/serialization/buffer_serializer.h>

#include "example::protocol/user_serializer.h"
#include "example::protocol/group_serializer.h"
#include "example::protocol/organization_serializer.h"

namespace bitrpc {
namespace example::protocol {

void register_serializers(BufferSerializer& serializer) {
    serializer.register_handler<User>(std::make_shared<UserSerializer>());
    serializer.register_handler<Group>(std::make_shared<GroupSerializer>());
    serializer.register_handler<Organization>(std::make_shared<OrganizationSerializer>());
}
}} // namespace bitrpc
