// Generated by BitRPC Protocol Generator
// File: User_serializer.cpp
// Language: Cpp
// Date: 2025-09-10 19:33:44


#include "example::protocol/user_serializer.h"

namespace bitrpc {
namespace example::protocol {

int UserSerializer::hash_code() const {
    return static_cast<int>(std::hash<std::string>{}("User"));
}

void UserSerializer::write(const void* obj, StreamWriter& writer) const {
    const auto& message = *static_cast<const User*>(obj);
    BitMask mask;

    // Bit mask group 0
    mask.set_bit(0, !is_default_string(message.name));
    mask.set_bit(1, !is_default_int32(message.age));
    mask.set_bit(2, !is_default_string(message.email));
    mask.write(writer);

    // Write field values
    if (mask.get_bit(0)) {
        writer.write_string(message.name);
    }
    if (mask.get_bit(1)) {
        writer.write_int32(message.age);
    }
    if (mask.get_bit(2)) {
        writer.write_string(message.email);
    }
}

void* UserSerializer::read(StreamReader& reader) const {
    auto message = std::make_unique<User>();

    // Read bit mask group 0
    BitMask mask0;
    mask0.read(reader);

    if (mask0.get_bit(0)) {
        message->name = reader.read_string();
    }
    if (mask0.get_bit(1)) {
        message->age = reader.read_int32();
    }
    if (mask0.get_bit(2)) {
        message->email = reader.read_string();
    }
    return message.release();
}

    bool is_default_string(const std::string& value) const;
    bool is_default_int32(const int32_t& value) const;

bool UserSerializer::is_default_string(const std::string& value) const {
    return value == "";
}
bool UserSerializer::is_default_int32(const int32_t& value) const {
    return value == 0;
}

}} // namespace bitrpc
