// Generated by BitRPC Protocol Generator
// File: IComplexServiceService.cs
// Language: CSharp
// Date: 2025-09-10 18:57:31


using System;
using System.Threading.Tasks;

namespace Example.Protocol.Server
{
    public interface IComplexServiceService
    {
    }
}
