// Generated by BitRPC Protocol Generator
// File: IOrganizationServiceService.cs
// Language: CSharp
// Date: 2025-09-10 19:33:44


using System;
using System.Threading.Tasks;

namespace Example.Protocol.Server
{
    public interface IOrganizationServiceService
    {
    }
}
