# Generated by BitRPC Protocol Generator
# File: iTestService_service.py
# Language: Python
# Date: 2025-10-08 00:56:42


from abc import ABC, abstractmethod
from typing import LoginRequest, GetUserRequest, EchoRequest, LoginResponse, GetUserResponse, EchoResponse, UserInfo

class ITestServiceService(ABC):
    """Interface for TestService service"""

    @abstractmethod
    async def Login_async(self, request: LoginRequest) -> LoginResponse:
        """Login method"""
        pass

    @abstractmethod
    async def GetUser_async(self, request: GetUserRequest) -> GetUserResponse:
        """GetUser method"""
        pass

    @abstractmethod
    async def Echo_async(self, request: EchoRequest) -> EchoResponse:
        """Echo method"""
        pass

    @abstractmethod
    async def StreamUsers_async(self, request: GetUserRequest) -> UserInfo:
        """StreamUsers method"""
        pass

